name: Java CI with Maven

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven settings
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          repositories: >
            [
              {
                "id": "github",
                "name": "GitHub emstryszawski Apache Maven Packages",
                "url": "https://maven.pkg.github.com/emstryszawski/foodbook-starter",
                "releases": {
                  "enabled": "true",
                  "updatePolicy": "always",
                  "checksumPolicy": "fail"
                },
                "snapshots": {
                  "enabled": "true",
                  "updatePolicy": "always",
                  "checksumPolicy": "fail"
                }
              }
            ]
          servers: >
            [
              {
                "id": "github",
                "username": "${secrets.GITHUB_USERNAME}",
                "password": "${secrets.GITHUB_TOKEN}"
              }
            ]
          output_file: .m2/settings.xml

      - run: echo .m2/settings.xml

      - name: Test
        run: mvn test --settings .m2/settings.xml
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: mvn -B package --file pom.xml --settings .m2/settings.xml
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}